-- +goose Up

-- Refresh tokens are opaque, high-entropy random values generated by the
-- application; only a SHA-256 hash is ever persisted, so a leaked database
-- row cannot be replayed as a session. Each row is one issued session and
-- is revocable independently (logout, admin-forced logout, rotation on
-- refresh).
CREATE TABLE refresh_tokens (
    id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id       uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash    text NOT NULL,
    expires_at    timestamptz NOT NULL,
    revoked_at    timestamptz,
    created_at    timestamptz NOT NULL DEFAULT now(),
    last_used_at  timestamptz,
    CONSTRAINT refresh_tokens_token_hash_unique UNIQUE (token_hash)
);

CREATE INDEX refresh_tokens_user_id_idx ON refresh_tokens(user_id);

-- +goose Down
DROP TABLE refresh_tokens;
